create table if not exists public.nominas (
  id bigint generated by default as identity primary key,
  year integer not null,
  month integer not null check (month between 1 and 12),
  item text not null,
  amount numeric(14, 2) not null,
  category text not null,
  subcategory text not null,
  file_id text not null,
  file_name text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_nominas_periodo on public.nominas (year, month);
create index if not exists idx_nominas_file_id on public.nominas (file_id);

create table if not exists public.control (
  id bigint generated by default as identity primary key,
  file_id text not null,
  file_name text not null,
  md5_drive text,
  source_folder_breadcrumb text,
  renamed_to text,
  target_folder_breadcrumb text,
  rules_version text,
  processed_at_utc timestamptz not null default now(),
  status text not null,
  error text
);

create unique index if not exists uq_control_file_id on public.control (file_id);
create index if not exists idx_control_md5_drive on public.control (md5_drive);
create index if not exists idx_control_processed_at on public.control (processed_at_utc desc);
